version: '3'
services:
    app:
        build:
            dockerfile: Dockerfile
        image: vite-ts
        container_name: vite-ts-module

        # 本地8080端口映射到nginx的80端口
        ports:
            - 8080:80
        restart: always
